#!/bin/bash -f
# Vivado (TM) v2016.4 (64-bit)
#
# Filename    : base_soc.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Nov 09 14:13:55 CST 2021
# IP Build 1755317 on Mon Jan 23 20:30:07 MST 2017 
#
# usage: base_soc.sh [-help]
# usage: base_soc.sh [-lib_map_path]
# usage: base_soc.sh [-noclean_files]
# usage: base_soc.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base_soc.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm microblaze_v10_0_1 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_10 blk_mem_gen_v8_3_5 axi_lite_ipif_v3_0_4 axi_intc_v4_1_9 mdm_v3_2_8 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_11 fifo_generator_v13_1_3 axi_data_fifo_v2_1_10 axi_crossbar_v2_1_12 lib_cdc_v1_0_2 lib_bmg_v1_0_7 lib_fifo_v1_0_7 axi_ethernetlite_v3_0_9 proc_sys_reset_v5_0_10 interrupt_control_v3_1_4 axi_gpio_v2_0_13 dist_mem_gen_v8_0_11 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_quad_spi_v3_2_10 axi_uartlite_v2_0_15 axi_timer_v2_0_13 axi_protocol_converter_v2_1_11 axi_clock_converter_v2_1_10 axi_dwidth_converter_v2_1_11)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "base_soc.sh - Script generated by export_simulation (Vivado v2016.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "/mnt/Storm/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/mnt/Storm/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/mnt/Storm/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v10_0_1 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/18bd/hdl/microblaze_v10_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_microblaze_0_0/sim/base_soc_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/162e/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_dlmb_v10_0/sim/base_soc_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_ilmb_v10_0/sim/base_soc_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_10 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/f4d9/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_dlmb_bram_if_cntlr_0/sim/base_soc_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_ilmb_bram_if_cntlr_0/sim/base_soc_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/6273/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_lmb_bram_0/sim/base_soc_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_9 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/a811/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_microblaze_0_axi_intc_0/sim/base_soc_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_8 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/71de/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mdm_1_0/sim/base_soc_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_clk_wiz_1_0/base_soc_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_clk_wiz_1_0/base_soc_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/0b6b/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/564d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_3 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/564d/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/564d/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/39ba/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/896d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_xbar_0/sim/base_soc_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_bmg_v1_0_7 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/38e8/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_7 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/5ab6/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_ethernetlite_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/f627/hdl/axi_ethernetlite_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_axi_ethernetlite_0_0/sim/base_soc_axi_ethernetlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_mux.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_row_col.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_state.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_common.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_queue.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_col_mach.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_cntrl.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_cntrl.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_mach.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_round_robin_arb.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_common.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_select.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_mach.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_mc.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_compare.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_wr_data.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_cmd.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_top.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_rd_data.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_fi_xor.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_buf.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_gen.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_clk_ibuf.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_infrastructure.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_tempmon.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_or.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_and.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_cc.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_pd.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_top.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_meta.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_top.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_edge_store.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_calib_top.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_init.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_tap_base.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_mem_intfc.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/base_soc_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_mig_7series_0_0/base_soc_mig_7series_0_0/user_design/rtl/base_soc_mig_7series_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_xbar_2/sim/base_soc_xbar_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_rst_mig_7series_0_83M_0/sim/base_soc_rst_mig_7series_0_83M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/e956/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_13 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/4f16/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_axi_gpio_0_0/sim/base_soc_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_axi_gpio_1_0/sim/base_soc_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/ec0d/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_10 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/e7ca/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_axi_quad_spi_0_0/sim/base_soc_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_15 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/2479/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_axi_uartlite_0_0/sim/base_soc_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_xbar_3/sim/base_soc_xbar_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_timer_v2_0_13 $vhdlan_opts \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/3edf/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_axi_timer_0_0/sim/base_soc_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/hdl/base_soc.v" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7102/src/pmod_concat.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_pmod_bridge_0_1/sim/base_soc_pmod_bridge_0_1.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_pmod_bridge_1_0/sim/base_soc_pmod_bridge_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_axi_gpio_2_0/sim/base_soc_axi_gpio_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_pmod_bridge_2_0/sim/base_soc_pmod_bridge_2_0.v" \
    "$ref_dir/../../../bd/base_soc/ipshared/2e37/xlconcat.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_xlconcat_0_0/sim/base_soc_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/c636/hdl/pulseLength.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/c636/hdl/PWM_Analyzer_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/c636/hdl/PWM_Analyzer_v1_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_PWM_Analyzer_0_0/sim/Pmod_Dual_MAXSONAR_PWM_Analyzer_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_PWM_Analyzer_1_0/sim/Pmod_Dual_MAXSONAR_PWM_Analyzer_1_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_xbar_0/sim/Pmod_Dual_MAXSONAR_xbar_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/c49f/xlslice.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_xlslice_0_0/sim/Pmod_Dual_MAXSONAR_xlslice_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_xlslice_0_1/sim/Pmod_Dual_MAXSONAR_xlslice_0_1.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/e147/xlconstant.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_xlconstant_0_0/sim/Pmod_Dual_MAXSONAR_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_xlconstant_1_0/sim/Pmod_Dual_MAXSONAR_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/df1b/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/src/Pmod_Dual_MAXSONAR_auto_pc_1/sim/Pmod_Dual_MAXSONAR_auto_pc_1.v" \
    "$ref_dir/../../../bd/base_soc/ipshared/5e35/src/Pmod_Dual_MAXSONAR.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/sim/base_soc_Pmod_Dual_MAXSONAR_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_axi_gpio_0_0/sim/Pmod_DHB1_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/af01/hdl/posCounter.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/af01/hdl/posManager.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/af01/hdl/MotorFeedback_v1_0_S00_AXI.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/af01/hdl/MotorFeedback_v1_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_MotorFeedback_0_0/sim/Pmod_DHB1_MotorFeedback_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/61d4/hdl/PWM_AXI.sv" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/61d4/hdl/PWM_v2_0.sv" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_PWM_0_0/sim/Pmod_DHB1_PWM_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlslice_0_0/sim/Pmod_DHB1_xlslice_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlslice_0_1/sim/Pmod_DHB1_xlslice_0_1.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlslice_0_2/sim/Pmod_DHB1_xlslice_0_2.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlslice_0_3/sim/Pmod_DHB1_xlslice_0_3.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlconcat_0_0/sim/Pmod_DHB1_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlconcat_0_1/sim/Pmod_DHB1_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlslice_0_4/sim/Pmod_DHB1_xlslice_0_4.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlslice_0_5/sim/Pmod_DHB1_xlslice_0_5.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xlconstant_0_0/sim/Pmod_DHB1_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_xbar_0/sim/Pmod_DHB1_xbar_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_auto_pc_0/sim/Pmod_DHB1_auto_pc_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/src/Pmod_DHB1_auto_pc_1/sim/Pmod_DHB1_auto_pc_1.v" \
    "$ref_dir/../../../bd/base_soc/ipshared/4519/src/Pmod_DHB1.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/sim/base_soc_Pmod_DHB1_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/8479/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/a4c8/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/100a" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_Dual_MAXSONAR_0_2/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../embedded_systems_lab.srcs/sources_1/bd/base_soc/ip/base_soc_Pmod_DHB1_0_0/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_ds_0/sim/base_soc_auto_ds_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_pc_0/sim/base_soc_auto_pc_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_us_0/sim/base_soc_auto_us_0.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_ds_1/sim/base_soc_auto_ds_1.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_ds_2/sim/base_soc_auto_ds_2.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_pc_1/sim/base_soc_auto_pc_1.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_pc_2/sim/base_soc_auto_pc_2.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_ds_3/sim/base_soc_auto_ds_3.v" \
    "$ref_dir/../../../bd/base_soc/ip/base_soc_auto_us_1/sim/base_soc_auto_us_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base_soc xil_defaultlib.glbl -o base_soc_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_soc_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base_soc.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/mnt/Rogue/projects/Vivado/embedded_systems_lab/embedded_systems_lab.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_soc_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc base_soc_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base_soc.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base_soc.sh [-help]\n\
Usage: base_soc.sh [-lib_map_path]\n\
Usage: base_soc.sh [-reset_run]\n\
Usage: base_soc.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
